name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Setup variables
      uses: actions/github-script@v7
      with:
        script: core.exportVariable('GITHUB_SHA_SHORT', context.sha.substring(0, 7))

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Configure Win64
      run: cmake -B ${{github.workspace}}/build-x64 -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCONFIG_BUILD_GLSLANG=ON

    - name: Configure Win32
      run: cmake -B ${{github.workspace}}/build-win32 -A Win32 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCONFIG_BUILD_GLSLANG=OFF

    - name: Build Game for Win64
      run: cmake --build ${{github.workspace}}/build-x64 --config ${{env.BUILD_TYPE}}

    - name: Build Dedicated Server for Win32
      run: cmake --build ${{github.workspace}}/build-win32 --config ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: q2rtx-windows-${{env.GITHUB_SHA_SHORT}}
        path: |
          q2rtx.exe
          q2rtxded.exe
          q2rtxded-x86.exe
          baseq2/
          rogue/
          license.txt
          notice.txt

  build-linux-x86_64:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest

    steps:
    - name: Setup variables
      uses: actions/github-script@v7
      with:
        script: core.exportVariable('GITHUB_SHA_SHORT', context.sha.substring(0, 7))

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update CMake
      run: |
        wget -q https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.tar.gz
        tar xzf cmake-4.1.2-linux-x86_64.tar.gz
        echo "CMAKE=$PWD/cmake-4.1.2-linux-x86_64/bin/cmake" >> $GITHUB_ENV

    - name: Configure
      run: |
        ${{ env.CMAKE }} --version
        CC=gcc-14 CXX=g++-14 ${{ env.CMAKE }} -B ${{github.workspace}}/build -GNinja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCONFIG_BUILD_GLSLANG=ON

    - name: Build Game
      run: |
        cd ${{github.workspace}}/build
        ninja

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: q2rtx-linux-x86_64-${{env.GITHUB_SHA_SHORT}}
        path: |
          q2rtx
          q2rtxded
          baseq2/
          rogue/
          license.txt
          notice.txt
